# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"

env:
  - DJANGO_REST_VERSION=3.8.0 DJANGO_VERSION="==2.2"
  - DJANGO_REST_VERSION=3.9.3 DJANGO_VERSION="==3.2"
  - DJANGO_REST_VERSION=3.12.4 DJANGO_VERSION=">=4.0"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q djangorestframework==$DJANGO_REST_VERSION Django$DJANGO_VERSION
  - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: python runtests.py
